version: "3"
services:
        filetransfer:
            #build:
            #context: ./dockerfile
            #dockerfile: gdrive
                image: thanakijwanavit/transfersh:gdrive
                volumes:
                        - ./filecache:/tmp
                        - ./gdrivecreden:/credentials
                        - ./gdriveconfig:/local_config
                ports:
                        - "8080:8080"
                networks:
                        - overlay
                deploy:
                        replicas: 1
networks:
        overlay:
