version: "3.7"
services:
        filetransfer:
                build:
                        context: ./dockerfile
                        dockerfile: gdrive
                image: thanakijwanavit/transfersh:armlocal
                volumes:
                        - filecache:/tmp
                        - ./gdrivecreden:/credentials
                ports:
                        - "8080:8080"
                networks:
                        - overlay
                entrypoint: /bin/sh
                deploy:
                        replicas: 1
volumes:
        filecache:
networks:
        overlay:
