version: "3.7"
services:
        filetransfer:
                image: thanakijwanavit/transfer.sh:armgdrive
                volumes:
                        - filecache:/tmp
                        - ./gdrivecreden:/credentials
                        - ./gdriveconfig:/gdrive-local-config-path
                ports:
                        - "8080:8080"
                networks:
                        - overlay
                deploy:
                        replicas: 1
volumes:
        filecache:
networks:
        overlay:
